FROM chbrandt/voublazars:latest

MAINTAINER "Carlos Brandt <carloshenriquebrandt at gmail>"

RUN cd /VOU_Blazars && git pull      		&&\
    cd /VOU_Blazars/bin/fort			&&\
    chmod +x compile.sh && ./compile.sh
