FROM chbrandt/voublazars:latest

MAINTAINER "Carlos Brandt <carloshenriquebrandt at gmail>"

ARG TAG="v1.94"

RUN cd /VOU_Blazars           &&\
    git fetch --all           &&\
    git checkout "$TAG"       &&\
    cd /VOU_Blazars/bin/fort  &&\
    chmod +x compile.sh       &&\
    ./compile.sh
